### ISSUE TITLE
Majority isn't always num. players / 2 +1

### ISSUE THREAD

**Issue by willyyang** [paulliwali/almondsandcashews#22]
4 Players. A B C D
A has 2 votes
B has 1 vote
D has 1 vote

A should be voted out. This doesn't work atm.

**Comment by paulliwali** [comment]
The algorithm for that majority votes is something along the lines of:

Votes on a person > votes left + votes on second most player.

Not sure if it is worth to pursue that rather than just check once at the
end of all votes.

**Comment by willyyang** [comment]
ya so I check once at end of all votes. :)
