### ISSUE TITLE
Create a way for public to submit new items

### ISSUE THREAD

**Issue by paulliwali** [paulliwali/almondsandcashews#4]
Research a way to change the database while it is live...?
Or a way to reference the items.js file so others can add to it?

**Comment by willyyang** [comment]
This should be interesting. Will look into it

**Comment by paulliwali** [comment]
An simple way might be to have a special user with that can have access to a template view specifically used to add item pairs?

**Comment by paulliwali** [comment]
e09d56dda969dc456f979fce66f2ae232d36a43d
