### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by paulliwali** [paulliwali/almondsandcashews#5]

**Comment by willyyang** [comment]
?!

**Comment by paulliwali** [comment]
Overall theme overhaul and a logo for the game

**Comment by paulliwali** [comment]
Amelia will work on something. Preliminary idea is: Almond & Cashews with an Almond in the O and lots of cashews in the word cashew. Sans Serif type font for Almond and Cursive for Cashews.

**Comment by paulliwali** [comment]
0b2b59f158eea17a4f7a220c63af2109e08033b0
